### ISSUE TITLE
Empty triples during training

### ISSUE THREAD

**Issue by atong28** [MeLeLBGU/SaGe#15]
I was doing a SaGe training run and kept getting the following error:
```multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/AnthonyTong/.conda/envs/tswap/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/AnthonyTong/TokenizerSwap/libraries/SaGe/src/sage_tokenizer/utils.py", line 243, in sage_per_chunk
    compute_losses(losses, triples, embeddings)
  File "/home/AnthonyTong/TokenizerSwap/libraries/SaGe/src/sage_tokenizer/utils.py", line 132, in compute_losses
    target_ids, context_ids, count = zip(*[(target_id, context_id, count) for (_, target_id, context_id), count in all_triples.items()])
ValueError: not enough values to unpack (expected 3, got 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/AnthonyTong/TokenizerSwap/libraries/SaGe/src/main.py", line 65, in <module>
    vocab_builder.build_vocab(
  File "/home/AnthonyTong/TokenizerSwap/libraries/SaGe/src/sage_tokenizer/SaGeVocabBuilder.py", line 100, in build_vocab
    total_tokens, total_triples, token_to_losses, ablated_sizes = run_sage_parallel(embeddings,
  File "/home/AnthonyTong/TokenizerSwap/libraries/SaGe/src/sage_tokenizer/utils.py", line 167, in run_sage_parallel
    losses, total_tokens, total_triples, ab_sizes = res.get()
  File "/home/AnthonyTong/.conda/envs/tswap/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: not enough values to unpack (expected 3, got 0)
```

It seems like the trainer assumes that SaGe always has a partial corpus left in the last chunk:

In `sage_per_chunk()` from `utils.py`:
```python
# compute for final partial chunk
compute_losses(losses, triples, embeddings)
total_triples += len(triples)
```
But if the triples dictionary is empty, the unpacking in `compute_losses` causes the error:
```python
target_ids, context_ids, count = zip(*[(target_id, context_id, count) for (_, target_id, context_id), count in all_triples.items()])
```
Where all_triples is empty so we cannot unpack an empty object. I believe the fix is simple, by just adding a check for all_triples being nonempty in `sage_per_chunk()`:
```python
if triples:
    # compute for final partial chunk
    compute_losses(losses, triples, embeddings)
    total_triples += len(triples)
```

Thanks.

**Comment by yuvalpinter** [comment]
Hi,

Thanks for alerting us to this bug. Your description makes sense to me. If you'd like to submit a pull request, we'd be happy to merge.

Best,
-- Yuval
